### ISSUE TITLE
Bulb color feedback not working

### ISSUE THREAD

**Issue by isaiahfranco** [bitfocus/companion-module-tplink-kasasmartbulb#1]
Hello, I'm playing around with the TP-Link Kasa Smart Bulb module, and everything seems to be working fine except for the bulb color feedback. Is it just me, or is that function not working properly? I have a KL125, KL130, and KL135.

Thanks!

**Comment by josephdadams** [comment]
Does the power state feedback work? What is the interval update rate in the config?

**Comment by isaiahfranco** [comment]
Power state works just fine. Interval is set to 100 but I'll probably end up pushing it to 1000.

**Comment by isaiahfranco** [comment]
@josephdadams Hey dude, just checking in to see if you've had time to take a look at this yet. Thanks!

**Comment by josephdadams** [comment]
Nope
